### ISSUE TITLE
Wrong ffmpegloc path on Ubuntu/Mint

### ISSUE THREAD

**Issue by vokiel** [raguay/ShowVideoFileProperties#2]
The path specified in https://github.com/raguay/ShowVideoFileProperties/blob/master/ShowVideoFileProperties.json#L2 is not right.

For example on Mint 18 the right path is `/usr/bin/ffmpeg`, so maybe it would be better to discover it on first run and then add it to the config file. Or just use `ffmpeg` which will be discovered by OS itself.

**Comment by raguay** [comment]
That is why I made it a config file option. You have to edit the
User/ShowVideoFileProperties (Linux).json in the Plugins directory. Just
change the path used for ffmpeg there and it will work. Every system is
different and on some system the Python os.execute() doesn't always
discover it correctly. For example, on a Mac, if you install it with
Homebrew, it's not really discoverable with the os.execute() command.

Richard
